config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :statuses
  resources :roles
  resources :incoming_mails
  resources :outgoing_mails
  resources :sections
  resources :users
  get 'home/index'
  
  root "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/incoming_mail.rb
class IncomingMail < ApplicationRecord
  belongs_to :user
  belongs_to :section
  has_many :comments, as: :commentable
end

app/controllers/incoming_mails_controller.rb
class IncomingMailsController < ApplicationController
  before_action :set_incoming_mail, only: [:show, :edit, :update, :destroy]

  # GET /incoming_mails
  # GET /incoming_mails.json
  def index
    @incoming_mails = IncomingMail.all
  end

  # GET /incoming_mails/1
  # GET /incoming_mails/1.json
  def show
  end

  # GET /incoming_mails/new
  def new
    @incoming_mail = IncomingMail.new
  end

  # GET /incoming_mails/1/edit
  def edit
  end

  # POST /incoming_mails
  # POST /incoming_mails.json
  def create
    @incoming_mail = IncomingMail.new(incoming_mail_params)

    respond_to do |format|
      if @incoming_mail.save
        format.html { redirect_to @incoming_mail, notice: 'Incoming mail was successfully created.' }
        format.json { render :show, status: :created, location: @incoming_mail }
      else
        format.html { render :new }
        format.json { render json: @incoming_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incoming_mails/1
  # PATCH/PUT /incoming_mails/1.json
  def update
    respond_to do |format|
      if @incoming_mail.update(incoming_mail_params)
        format.html { redirect_to @incoming_mail, notice: 'Incoming mail was successfully updated.' }
        format.json { render :show, status: :ok, location: @incoming_mail }
      else
        format.html { render :edit }
        format.json { render json: @incoming_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incoming_mails/1
  # DELETE /incoming_mails/1.json
  def destroy
    @incoming_mail.destroy
    respond_to do |format|
      format.html { redirect_to incoming_mails_url, notice: 'Incoming mail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incoming_mail
      @incoming_mail = IncomingMail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incoming_mail_params
      params.require(:incoming_mail).permit(:title, :description)
    end
end

app/helpers/incoming_mails_helper.rb
module IncomingMailsHelper
end

app/views/incoming_mails/_form.html.erb
<%= form_with(model: incoming_mail, local: true) do |form| %>
  <% if incoming_mail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(incoming_mail.errors.count, "error") %> prohibited this incoming_mail from being saved:</h2>

      <ul>
      <% incoming_mail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :incoming_mail_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :incoming_mail_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/incoming_mails/edit.html.erb
<h1>Editing Incoming Mail</h1>

<%= render 'form', incoming_mail: @incoming_mail %>

<%= link_to 'Show', @incoming_mail %> |
<%= link_to 'Back', incoming_mails_path %>

app/views/incoming_mails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incoming Mails</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incoming_mails.each do |incoming_mail| %>
      <tr>
        <td><%= incoming_mail.title %></td>
        <td><%= incoming_mail.description %></td>
        <td><%= link_to 'Show', incoming_mail %></td>
        <td><%= link_to 'Edit', edit_incoming_mail_path(incoming_mail) %></td>
        <td><%= link_to 'Destroy', incoming_mail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incoming Mail', new_incoming_mail_path %>

app/views/incoming_mails/new.html.erb
<h1>New Incoming Mail</h1>

<%= render 'form', incoming_mail: @incoming_mail %>

<%= link_to 'Back', incoming_mails_path %>

app/views/incoming_mails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @incoming_mail.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @incoming_mail.description %>
</p>

<%= link_to 'Edit', edit_incoming_mail_path(@incoming_mail) %> |
<%= link_to 'Back', incoming_mails_path %>